# Generated by Django 3.1.4 on 2020-12-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('avatar', models.JSONField()),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('total_posts', models.IntegerField()),
                ('url', models.CharField(max_length=100)),
                ('uuid', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
